spring:
  application:
    name: todo_application
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: Application
    password: 20190506
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
server:
  servlet:
    context-path: /todo
