spring:
  application:
    name: todo_application
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ponram
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update
server:
  servlet:
    context-path: /your-context-path
